name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore BooksChampions/BooksChampions.sln

      - name: Build application
        run: dotnet build BooksChampions/BooksChampions.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish application
        run: dotnet publish BooksChampions/Web/Web.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9B466CDC6C114DF196C30EF899DF070A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F2684676D04B42358C28EB53E0F60AA9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_961FB76CFD6E404EA7EF0319FD2BE5A0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "api-proyecto-tup-2025"
          slot-name: "Production"
          package: .
