name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore BooksChampions/Web/Web.csproj

      - name: Build application
        run: dotnet build BooksChampions/Web/Web.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish application
        run: dotnet publish BooksChampions/Web/Web.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./webapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "api-proyecto-tup-2025"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./webapp"
